services:
  postgres:
    image: postgres:17
    container_name: arena-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: arena
      POSTGRES_USER: arena
      POSTGRES_PASSWORD: arena

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U arena -d arena"]
      interval: 5s
      timeout: 5s
      retries: 10

    ports:
      - "5432:5432"

    volumes:
      - arenaapi_postgres-data:/var/lib/postgresql/data

volumes:
  arenaapi_postgres-data:
